#!/usr/bin/env node

var thermometers=require("temper1x");
var devices = thermometers.getDevices();

console.log('./pull')
console.log('  --path')
devices.forEach(function(device) { 
  console.log('      ' + device)
})

