#!/usr/bin/env node

var exec = require('child_process').exec;
console.log('Installing...')
exec('which rpi-update', function(err, stdout, stderr) {
  if (stdout) {
    // We are on raspbian, try nonstandard install
    var child = exec('cd ' + __dirname + '; npm install commander; cd node_modules; git clone git@github.com:rjsteinert/temper1x.raspbian.git;')
    child.stdout.on('data', function(data) {
      console.log(data)
    })
    child.stderr.on('data', function(data) {
      console.log(data)
    })
  }
  else {
    // We are not on raspbian, try standard install
    var child = exec('cd ' + __dirname + '; npm install;')
    child.stdout.on('data', function(data) {
      console.log(data)
    })
    child.stderr.on('data', function(data) {
      console.log(data)
    })
  })
