#!/usr/bin/env node

var exec = require('child_process').exec;
var program = require('commander');
var log = function(msg) {
  if (program.verbose) {
    console.log(msg)
  }
}
 
program
  .version('0.0.0')
  .option('-p, --path [path]', 'Set a path to the temper1 device. Detect the path by running the detect command.', '')
  .option('-t, --timeout [timeout]', 'How long before trying the `try` command again. If you are on a slow system you may need to increase this.', '1000')
  .option('--verbose')
  .parse(process.argv);

if (program.path == '') {
  console.log('You must define a path to the temper1 USB sensor.')
  console.log('Ex.')
  console.log('./pull --path USB_0c45_7401_14100000')
  console.log('')
  exec('./detect', function(err, stdout, stderr) {
    console.log(stdout)
    process.exit()
  })
}

var poll = function() {
  log('trying...')
  var cmd = __dirname + '/try --path ' + program.path
  log(cmd)
  var child = exec(cmd, function(err, stdout, stderr) {
    if (stdout) {
      console.log(stdout)
      process.exit(1)
    }
  })
  setTimeout(function() {
    child.kill('SIGKILL')
    poll()
  }, program.timeout)
}

poll()

