#!/usr/bin/env node

var exec = require('child_process').exec;
var timeout = 100
var program = require('commander');
 
program
  .version('0.0.0')
  .option('-p, --path [path]', 'Set a path to the temper1 device. Detect the path by running the detect command.', '')
  .parse(process.argv);

if (program.path == '') {
  console.log('You must define a path to the temper1 USB sensor.')
  console.log('Ex.')
  console.log('./pull --path USB_0c45_7401_14100000')
  console.log('')
  exec('./detect', function(err, stdout, stderr) {
    console.log(stdout)
    process.exit()
  })
}

var poll = function() {
  var cmd = __dirname + '/try --path ' + program.path
  var child = exec(cmd, function(err, stdout, stderr) {
    if (stdout) {
      console.log(stdout)
      process.exit(1)
    }
  })
  setTimeout(function() {
    child.kill('SIGKILL')
    poll()
  }, timeout)
}

poll()

