#!/usr/bin/env node

var temper1x = require("temper1x")
var program = require('commander')
 
var devices = temper1x.getDevices()
program
  .version('0.0.0')
  .option('-p, --path [path]', 'Set a path to the temper1 device. Detect the path by running the detect command.', '')
  .parse(process.argv)

if (program.path == '') {
  console.log('You must define a path to the temper1 USB sensor.')
  console.log('Ex.')
  console.log('./pull --path USB_0c45_7401_14100000')
  console.log('')
  exec('./detect', function(err, stdout, stderr) {
    console.log(stdout)
    process.exit()
  })
}

temper1x.readTemperature(program.path, function(err, value) {
  if (err) console.log(err)
  console.log(value)
})
